name: build-and-push-image

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push amd64 image
        uses: docker/build-push-action@v4
        with:
          context: amd64
          file: ./amd64/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/invoke-atomicredteam:amd64

      - name: Build and push arm64 image
        uses: docker/build-push-action@v4
        with:
          context: arm64
          platforms: linux/arm64
          file: ./arm64/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/invoke-atomicredteam:arm64
