name: Publish Docker containers
on:
  push:
    branches:
      - main

jobs:
  build-publish-containers:
    name: Build and Publish Containers
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 3
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - os: ubuntu-latest
            file: Dockerfile
            tag: ${{ secrets.DOCKER_USERNAME }}/invoke-atomicredteam:${{ github.event.release.tag_name }}-linux-amd64
          - os: windows-latest
            file: Dockerfile
            tag: ${{ secrets.DOCKER_USERNAME }}/invoke-atomicredteam:${{ github.event.release.tag_name }}-windows-amd64
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Docker Build
        run: |
          docker build -f ${{ matrix.file }} -t ${{ matrix.tag }} .
      - name: Docker Push
        run: |
          docker push ${{ matrix.tag }}

  publish-manfiest:
    name: Publish Manifest
    runs-on: ubuntu-latest
    needs: build-publish-containers
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Docker Manifest
        run: |
          docker manifest create cyberbuff/invoke-atomicredteam:${{ github.event.release.tag_name }} \
            --amend ${{ secrets.DOCKER_USERNAME }}/invoke-atomicredteam:${{ github.event.release.tag_name }}-linux-amd64 \
            --amend ${{ secrets.DOCKER_USERNAME }}/invoke-atomicredteam:${{ github.event.release.tag_name }}-windows-amd64
      - name: Docker Annotate
        run: |
          docker manifest annotate --os windows --arch amd64 \
            ${{ secrets.DOCKER_USERNAME }}/invoke-atomicredteam:${{ github.event.release.tag_name }} ${{ secrets.DOCKER_USERNAME }}/invoke-atomicredteam:${{ github.event.release.tag_name }}-windows-amd64
      - name: Docker Push
        run: |
          docker manifest push ${{ secrets.DOCKER_USERNAME }}/invoke-atomicredteam:${{ github.event.release.tag_name }}
